//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webtest_ThuVien
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;


    public class WebTest1Coded : WebTest
    {

        public WebTest1Coded()
        {
            this.PreAuthenticate = true;
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("http://thuvien/index.php");
            request1.ThinkTime = 4;
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("http://thuvien/images/clip2.swf");
            request3.ThinkTime = 189;
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("http://thuvien/index.php");
            request4.QueryStringParameters.Add("mod", "sach_tooltip", false, false);
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request5.ThinkTime = 2;
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("http://thuvien/index.php");
            request6.QueryStringParameters.Add("mod", "chitiet_sach", false, false);
            request6.QueryStringParameters.Add("cat", "11", false, false);
            request6.QueryStringParameters.Add("masach", "2", false, false);
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request7.ThinkTime = 160;
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest("http://thuvien/index.php");
            request8.QueryStringParameters.Add("mod", "sach_tooltip", false, false);
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request9.ThinkTime = 3;
            yield return request9;
            request9 = null;

            WebTestRequest request10 = new WebTestRequest("http://thuvien/index.php");
            request10.QueryStringParameters.Add("mod", "chitiet_sach", false, false);
            request10.QueryStringParameters.Add("cat", "11", false, false);
            request10.QueryStringParameters.Add("masach", "2", false, false);
            yield return request10;
            request10 = null;

            WebTestRequest request11 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request11.ThinkTime = 2;
            yield return request11;
            request11 = null;

            WebTestRequest request12 = new WebTestRequest("http://thuvien/index.php");
            request12.QueryStringParameters.Add("mod", "sach_tooltip", false, false);
            yield return request12;
            request12 = null;

            WebTestRequest request13 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request13.ThinkTime = 7;
            yield return request13;
            request13 = null;

            WebTestRequest request14 = new WebTestRequest("http://thuvien/index.php");
            request14.QueryStringParameters.Add("mod", "tapchi_tooltip", false, false);
            yield return request14;
            request14 = null;

            WebTestRequest request15 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request15.ThinkTime = 1;
            yield return request15;
            request15 = null;

            WebTestRequest request16 = new WebTestRequest("http://thuvien/index.php");
            request16.QueryStringParameters.Add("mod", "chitiet_sach", false, false);
            request16.QueryStringParameters.Add("cat", "3", false, false);
            request16.QueryStringParameters.Add("masach", "24", false, false);
            yield return request16;
            request16 = null;

            WebTestRequest request17 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            yield return request17;
            request17 = null;

            WebTestRequest request18 = new WebTestRequest("http://thuvien/index.php");
            request18.ThinkTime = 5;
            request18.QueryStringParameters.Add("mod", "tapchi_tooltip", false, false);
            yield return request18;
            request18 = null;

            WebTestRequest request19 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request19.ThinkTime = 3;
            yield return request19;
            request19 = null;

            WebTestRequest request20 = new WebTestRequest("http://thuvien/index.php");
            request20.QueryStringParameters.Add("mod", "chitiet_sach", false, false);
            request20.QueryStringParameters.Add("cat", "3", false, false);
            request20.QueryStringParameters.Add("masach", "28", false, false);
            yield return request20;
            request20 = null;

            WebTestRequest request21 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request21.ThinkTime = 2;
            yield return request21;
            request21 = null;

            WebTestRequest request22 = new WebTestRequest("http://thuvien/index.php");
            request22.QueryStringParameters.Add("mod", "tapchi_tooltip", false, false);
            yield return request22;
            request22 = null;

            WebTestRequest request23 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request23.ThinkTime = 2;
            yield return request23;
            request23 = null;

            WebTestRequest request24 = new WebTestRequest("http://thuvien/index.php");
            request24.QueryStringParameters.Add("mod", "luanvan_tooltip", false, false);
            yield return request24;
            request24 = null;

            WebTestRequest request25 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request25.ThinkTime = 4;
            yield return request25;
            request25 = null;

            WebTestRequest request26 = new WebTestRequest("http://thuvien/index.php");
            request26.QueryStringParameters.Add("mod", "chitiet_sach", false, false);
            request26.QueryStringParameters.Add("cat", "4", false, false);
            request26.QueryStringParameters.Add("masach", "67", false, false);
            yield return request26;
            request26 = null;

            WebTestRequest request27 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request27.ThinkTime = 3;
            yield return request27;
            request27 = null;

            WebTestRequest request28 = new WebTestRequest("http://thuvien/index.php");
            request28.QueryStringParameters.Add("mod", "luanvan_tooltip", false, false);
            yield return request28;
            request28 = null;

            WebTestRequest request29 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request29.ThinkTime = 52;
            yield return request29;
            request29 = null;

            WebTestRequest request30 = new WebTestRequest("http://thuvien/index.php");
            request30.QueryStringParameters.Add("mod", "chitiet_sach", false, false);
            request30.QueryStringParameters.Add("cat", "4", false, false);
            request30.QueryStringParameters.Add("masach", "67", false, false);
            yield return request30;
            request30 = null;

            WebTestRequest request31 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request31.ThinkTime = 2;
            yield return request31;
            request31 = null;

            WebTestRequest request32 = new WebTestRequest("http://thuvien/index.php");
            request32.QueryStringParameters.Add("mod", "luanvan_tooltip", false, false);
            ExtractHiddenFields extractionRule1 = new ExtractHiddenFields();
            extractionRule1.Required = true;
            extractionRule1.HtmlDecode = true;
            extractionRule1.ContextParameterName = "1";
            request32.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule1.Extract);
            yield return request32;
            request32 = null;

            WebTestRequest request33 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request33.ThinkTime = 31;
            yield return request33;
            request33 = null;

            WebTestRequest request34 = new WebTestRequest("http://thuvien/index.php");
            request34.QueryStringParameters.Add("mod", this.Context["$HIDDEN1.mod"].ToString(), false, false);
            request34.QueryStringParameters.Add("key1", "Nh%E1%BA%ADp+v%C3%A0o+t%E1%BB%AB+c%E1%BA%A7n+t%C3%ACm", false, false);
            request34.QueryStringParameters.Add("key2", "11", false, false);
            request34.QueryStringParameters.Add("key3", "All", false, false);
            yield return request34;
            request34 = null;

            WebTestRequest request35 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request35.ThinkTime = 3;
            yield return request35;
            request35 = null;

            WebTestRequest request36 = new WebTestRequest("http://thuvien/index.php");
            request36.QueryStringParameters.Add("mod", "chitiet_sach", false, false);
            request36.QueryStringParameters.Add("cat", "11", false, false);
            request36.QueryStringParameters.Add("masach", "4", false, false);
            ExtractHiddenFields extractionRule2 = new ExtractHiddenFields();
            extractionRule2.Required = true;
            extractionRule2.HtmlDecode = true;
            extractionRule2.ContextParameterName = "1";
            request36.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule2.Extract);
            yield return request36;
            request36 = null;

            WebTestRequest request37 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request37.ThinkTime = 2;
            yield return request37;
            request37 = null;

            WebTestRequest request38 = new WebTestRequest("http://thuvien/index.php");
            request38.QueryStringParameters.Add("mod", this.Context["$HIDDEN1.mod"].ToString(), false, false);
            request38.QueryStringParameters.Add("key1", "Nh%E1%BA%ADp+v%C3%A0o+t%E1%BB%AB+c%E1%BA%A7n+t%C3%ACm", false, false);
            request38.QueryStringParameters.Add("key2", "11", false, false);
            request38.QueryStringParameters.Add("key3", "All", false, false);
            yield return request38;
            request38 = null;

            WebTestRequest request39 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request39.ThinkTime = 2;
            yield return request39;
            request39 = null;

            WebTestRequest request40 = new WebTestRequest("http://thuvien/index.php");
            request40.QueryStringParameters.Add("mod", "chitiet_sach", false, false);
            request40.QueryStringParameters.Add("cat", "11", false, false);
            request40.QueryStringParameters.Add("masach", "6", false, false);
            ExtractHiddenFields extractionRule3 = new ExtractHiddenFields();
            extractionRule3.Required = true;
            extractionRule3.HtmlDecode = true;
            extractionRule3.ContextParameterName = "1";
            request40.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule3.Extract);
            yield return request40;
            request40 = null;

            WebTestRequest request41 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request41.ThinkTime = 2;
            yield return request41;
            request41 = null;

            WebTestRequest request42 = new WebTestRequest("http://thuvien/index.php");
            request42.QueryStringParameters.Add("mod", this.Context["$HIDDEN1.mod"].ToString(), false, false);
            request42.QueryStringParameters.Add("key1", "Nh%E1%BA%ADp+v%C3%A0o+t%E1%BB%AB+c%E1%BA%A7n+t%C3%ACm", false, false);
            request42.QueryStringParameters.Add("key2", "11", false, false);
            request42.QueryStringParameters.Add("key3", "All", false, false);
            ExtractHiddenFields extractionRule4 = new ExtractHiddenFields();
            extractionRule4.Required = true;
            extractionRule4.HtmlDecode = true;
            extractionRule4.ContextParameterName = "1";
            request42.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule4.Extract);
            yield return request42;
            request42 = null;

            WebTestRequest request43 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request43.ThinkTime = 18;
            yield return request43;
            request43 = null;

            WebTestRequest request44 = new WebTestRequest("http://thuvien/index.php");
            request44.QueryStringParameters.Add("mod", this.Context["$HIDDEN1.mod"].ToString(), false, false);
            request44.QueryStringParameters.Add("key1", "Nh%E1%BA%ADp+v%C3%A0o+t%E1%BB%AB+c%E1%BA%A7n+t%C3%ACm", false, false);
            request44.QueryStringParameters.Add("key2", "11", false, false);
            request44.QueryStringParameters.Add("key3", "23", false, false);
            yield return request44;
            request44 = null;

            WebTestRequest request45 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request45.ThinkTime = 8;
            yield return request45;
            request45 = null;

            WebTestRequest request46 = new WebTestRequest("http://thuvien/index.php");
            request46.QueryStringParameters.Add("mod", "chitiet_sach", false, false);
            request46.QueryStringParameters.Add("cat", "11", false, false);
            request46.QueryStringParameters.Add("masach", "3", false, false);
            request46.QueryStringParameters.Add("subcat", "23", false, false);
            ExtractHiddenFields extractionRule5 = new ExtractHiddenFields();
            extractionRule5.Required = true;
            extractionRule5.HtmlDecode = true;
            extractionRule5.ContextParameterName = "1";
            request46.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule5.Extract);
            yield return request46;
            request46 = null;

            WebTestRequest request47 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request47.ThinkTime = 7;
            yield return request47;
            request47 = null;

            WebTestRequest request48 = new WebTestRequest("http://thuvien/index.php");
            request48.QueryStringParameters.Add("mod", this.Context["$HIDDEN1.mod"].ToString(), false, false);
            request48.QueryStringParameters.Add("key1", "Nh%E1%BA%ADp+v%C3%A0o+t%E1%BB%AB+c%E1%BA%A7n+t%C3%ACm", false, false);
            request48.QueryStringParameters.Add("key2", "11", false, false);
            request48.QueryStringParameters.Add("key3", "23", false, false);
            yield return request48;
            request48 = null;

            WebTestRequest request49 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request49.ThinkTime = 2;
            yield return request49;
            request49 = null;

            WebTestRequest request50 = new WebTestRequest("http://thuvien/index.php");
            request50.QueryStringParameters.Add("mod", "chitiet_sach", false, false);
            request50.QueryStringParameters.Add("cat", "11", false, false);
            request50.QueryStringParameters.Add("masach", "40", false, false);
            request50.QueryStringParameters.Add("subcat", "23", false, false);
            ExtractHiddenFields extractionRule6 = new ExtractHiddenFields();
            extractionRule6.Required = true;
            extractionRule6.HtmlDecode = true;
            extractionRule6.ContextParameterName = "1";
            request50.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule6.Extract);
            yield return request50;
            request50 = null;

            WebTestRequest request51 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            yield return request51;
            request51 = null;

            WebTestRequest request52 = new WebTestRequest("http://thuvien/index.php");
            request52.ThinkTime = 5;
            request52.QueryStringParameters.Add("mod", this.Context["$HIDDEN1.mod"].ToString(), false, false);
            request52.QueryStringParameters.Add("key1", "Nh%E1%BA%ADp+v%C3%A0o+t%E1%BB%AB+c%E1%BA%A7n+t%C3%ACm", false, false);
            request52.QueryStringParameters.Add("key2", "11", false, false);
            request52.QueryStringParameters.Add("key3", "23", false, false);
            ExtractHiddenFields extractionRule7 = new ExtractHiddenFields();
            extractionRule7.Required = true;
            extractionRule7.HtmlDecode = true;
            extractionRule7.ContextParameterName = "1";
            request52.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule7.Extract);
            yield return request52;
            request52 = null;

            WebTestRequest request53 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request53.ThinkTime = 30;
            yield return request53;
            request53 = null;

            WebTestRequest request54 = new WebTestRequest("http://thuvien/index.php");
            request54.QueryStringParameters.Add("mod", this.Context["$HIDDEN1.mod"].ToString(), false, false);
            request54.QueryStringParameters.Add("key1", "kinh", false, false);
            request54.QueryStringParameters.Add("key2", "11", false, false);
            request54.QueryStringParameters.Add("key3", "13", false, false);
            yield return request54;
            request54 = null;

            WebTestRequest request55 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request55.ThinkTime = 3;
            yield return request55;
            request55 = null;

            WebTestRequest request56 = new WebTestRequest("http://thuvien/index.php");
            request56.QueryStringParameters.Add("mod", "chitiet_sach", false, false);
            request56.QueryStringParameters.Add("cat", "11", false, false);
            request56.QueryStringParameters.Add("masach", "54", false, false);
            request56.QueryStringParameters.Add("subcat", "13", false, false);
            ExtractHiddenFields extractionRule8 = new ExtractHiddenFields();
            extractionRule8.Required = true;
            extractionRule8.HtmlDecode = true;
            extractionRule8.ContextParameterName = "1";
            request56.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule8.Extract);
            yield return request56;
            request56 = null;

            WebTestRequest request57 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request57.ThinkTime = 2;
            yield return request57;
            request57 = null;

            WebTestRequest request58 = new WebTestRequest("http://thuvien/index.php");
            request58.QueryStringParameters.Add("mod", this.Context["$HIDDEN1.mod"].ToString(), false, false);
            request58.QueryStringParameters.Add("key1", "kinh", false, false);
            request58.QueryStringParameters.Add("key2", "11", false, false);
            request58.QueryStringParameters.Add("key3", "13", false, false);
            yield return request58;
            request58 = null;

            WebTestRequest request59 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request59.ThinkTime = 3;
            yield return request59;
            request59 = null;

            WebTestRequest request60 = new WebTestRequest("http://thuvien/index.php");
            request60.QueryStringParameters.Add("mod", "chitiet_sach", false, false);
            request60.QueryStringParameters.Add("cat", "11", false, false);
            request60.QueryStringParameters.Add("masach", "13", false, false);
            request60.QueryStringParameters.Add("subcat", "13", false, false);
            ExtractHiddenFields extractionRule9 = new ExtractHiddenFields();
            extractionRule9.Required = true;
            extractionRule9.HtmlDecode = true;
            extractionRule9.ContextParameterName = "1";
            request60.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule9.Extract);
            yield return request60;
            request60 = null;

            WebTestRequest request61 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request61.ThinkTime = 2;
            yield return request61;
            request61 = null;

            WebTestRequest request62 = new WebTestRequest("http://thuvien/index.php");
            request62.QueryStringParameters.Add("mod", this.Context["$HIDDEN1.mod"].ToString(), false, false);
            request62.QueryStringParameters.Add("key1", "kinh", false, false);
            request62.QueryStringParameters.Add("key2", "11", false, false);
            request62.QueryStringParameters.Add("key3", "13", false, false);
            ExtractHiddenFields extractionRule10 = new ExtractHiddenFields();
            extractionRule10.Required = true;
            extractionRule10.HtmlDecode = true;
            extractionRule10.ContextParameterName = "1";
            request62.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule10.Extract);
            yield return request62;
            request62 = null;

            WebTestRequest request63 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request63.ThinkTime = 10;
            yield return request63;
            request63 = null;

            WebTestRequest request64 = new WebTestRequest("http://thuvien/index.php");
            request64.QueryStringParameters.Add("mod", this.Context["$HIDDEN1.mod"].ToString(), false, false);
            request64.QueryStringParameters.Add("key1", "cao", false, false);
            request64.QueryStringParameters.Add("key2", "11", false, false);
            request64.QueryStringParameters.Add("key3", "All", false, false);
            yield return request64;
            request64 = null;

            WebTestRequest request65 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request65.ThinkTime = 2;
            yield return request65;
            request65 = null;

            WebTestRequest request66 = new WebTestRequest("http://thuvien/index.php");
            request66.QueryStringParameters.Add("mod", "chitiet_sach", false, false);
            request66.QueryStringParameters.Add("cat", "11", false, false);
            request66.QueryStringParameters.Add("masach", "8", false, false);
            ExtractHiddenFields extractionRule11 = new ExtractHiddenFields();
            extractionRule11.Required = true;
            extractionRule11.HtmlDecode = true;
            extractionRule11.ContextParameterName = "1";
            request66.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule11.Extract);
            yield return request66;
            request66 = null;

            WebTestRequest request67 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request67.ThinkTime = 4;
            yield return request67;
            request67 = null;

            WebTestRequest request68 = new WebTestRequest("http://thuvien/index.php");
            request68.QueryStringParameters.Add("mod", this.Context["$HIDDEN1.mod"].ToString(), false, false);
            request68.QueryStringParameters.Add("key1", "cao", false, false);
            request68.QueryStringParameters.Add("key2", "11", false, false);
            request68.QueryStringParameters.Add("key3", "All", false, false);
            yield return request68;
            request68 = null;

            WebTestRequest request69 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request69.ThinkTime = 9;
            yield return request69;
            request69 = null;

            WebTestRequest request70 = new WebTestRequest("http://thuvien/index.php");
            request70.QueryStringParameters.Add("mod", "chitiet_sach", false, false);
            request70.QueryStringParameters.Add("cat", "11", false, false);
            request70.QueryStringParameters.Add("masach", "9", false, false);
            ExtractHiddenFields extractionRule12 = new ExtractHiddenFields();
            extractionRule12.Required = true;
            extractionRule12.HtmlDecode = true;
            extractionRule12.ContextParameterName = "1";
            request70.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule12.Extract);
            yield return request70;
            request70 = null;

            WebTestRequest request71 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request71.ThinkTime = 2;
            yield return request71;
            request71 = null;

            WebTestRequest request72 = new WebTestRequest("http://thuvien/index.php");
            request72.QueryStringParameters.Add("mod", this.Context["$HIDDEN1.mod"].ToString(), false, false);
            request72.QueryStringParameters.Add("key1", "cao", false, false);
            request72.QueryStringParameters.Add("key2", "11", false, false);
            request72.QueryStringParameters.Add("key3", "All", false, false);
            ExtractHiddenFields extractionRule13 = new ExtractHiddenFields();
            extractionRule13.Required = true;
            extractionRule13.HtmlDecode = true;
            extractionRule13.ContextParameterName = "1";
            request72.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule13.Extract);
            yield return request72;
            request72 = null;

            WebTestRequest request73 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request73.ThinkTime = 66;
            yield return request73;
            request73 = null;

            WebTestRequest request74 = new WebTestRequest("http://thuvien/index.php");
            request74.Method = "POST";
            request74.ExpectedResponseUrl = "http://thuvien/index.php";
            request74.QueryStringParameters.Add("mod", this.Context["$HIDDEN1.mod"].ToString(), false, false);
            request74.QueryStringParameters.Add("key1", "cao", false, false);
            request74.QueryStringParameters.Add("key2", "11", false, false);
            request74.QueryStringParameters.Add("key3", "All", false, false);
            FormPostHttpBody request74Body = new FormPostHttpBody();
            request74Body.FormPostParameters.Add("kt_login_user", "12");
            request74Body.FormPostParameters.Add("kt_login_password", "123456");
            request74Body.FormPostParameters.Add("kt_login1", "Đăng nhập");
            request74.Body = request74Body;
            yield return request74;
            request74 = null;

            WebTestRequest request75 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            yield return request75;
            request75 = null;

            WebTestRequest request76 = new WebTestRequest("http://thuvien/images/clip2.swf");
            request76.ThinkTime = 8;
            yield return request76;
            request76 = null;

            WebTestRequest request77 = new WebTestRequest("http://thuvien/index.php");
            request77.QueryStringParameters.Add("mod", "user_cnthongtin", false, false);
            yield return request77;
            request77 = null;

            WebTestRequest request78 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request78.ThinkTime = 24;
            yield return request78;
            request78 = null;

            WebTestRequest request79 = new WebTestRequest("http://thuvien/index.php");
            request79.Method = "POST";
            request79.QueryStringParameters.Add("mod", "capnhatthongtinthanhcong", false, false);
            FormPostHttpBody request79Body = new FormPostHttpBody();
            request79Body.FormPostParameters.Add("old_Pass", "123456");
            request79Body.FormPostParameters.Add("Pass", "123456");
            request79Body.FormPostParameters.Add("re_Pass", "123456");
            request79Body.FormPostParameters.Add("Email", "ngocyen@gmail.com");
            request79Body.FormPostParameters.Add("SoDienThoai", "01682015963");
            request79Body.FormPostParameters.Add("KT_Update1", "Cập nhật");
            request79.Body = request79Body;
            yield return request79;
            request79 = null;

            WebTestRequest request80 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request80.ThinkTime = 5;
            yield return request80;
            request80 = null;

            WebTestRequest request81 = new WebTestRequest("http://thuvien/index.php");
            yield return request81;
            request81 = null;

            WebTestRequest request82 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            yield return request82;
            request82 = null;

            WebTestRequest request83 = new WebTestRequest("http://thuvien/images/clip2.swf");
            request83.ThinkTime = 7;
            yield return request83;
            request83 = null;

            WebTestRequest request84 = new WebTestRequest("http://thuvien/index.php");
            request84.QueryStringParameters.Add("mod", "thongtinmuontrasach", false, false);
            yield return request84;
            request84 = null;

            WebTestRequest request85 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request85.ThinkTime = 9;
            yield return request85;
            request85 = null;

            WebTestRequest request86 = new WebTestRequest("http://thuvien/admin/admincp_thuthu.php");
            request86.ThinkTime = 9;
            yield return request86;
            request86 = null;

            WebTestRequest request87 = new WebTestRequest("http://thuvien/admin/admincp_thuthu.php");
            request87.ThinkTime = 23;
            request87.QueryStringParameters.Add("mod", "list_thanhvien", false, false);
            yield return request87;
            request87 = null;

            WebTestRequest request88 = new WebTestRequest("http://thuvien/admin/admincp_thuthu.php");
            request88.QueryStringParameters.Add("mod", "list_lop", false, false);
            yield return request88;
            request88 = null;

            WebTestRequest request89 = new WebTestRequest("http://thuvien/includes/nxt/scripts/list.js.php");
            request89.ThinkTime = 10;
            yield return request89;
            request89 = null;

            WebTestRequest request90 = new WebTestRequest("http://thuvien/admin/admincp_thuthu.php");
            request90.QueryStringParameters.Add("mod", "list_sachthuthu", false, false);
            yield return request90;
            request90 = null;

            WebTestRequest request91 = new WebTestRequest("http://thuvien/includes/nxt/scripts/list.js.php");
            request91.ThinkTime = 6;
            yield return request91;
            request91 = null;

            WebTestRequest request92 = new WebTestRequest("http://thuvien/admin/admincp_thuthu.php");
            request92.QueryStringParameters.Add("mod", "list_phieumuonthuthu", false, false);
            yield return request92;
            request92 = null;

            WebTestRequest request93 = new WebTestRequest("http://thuvien/includes/nxt/scripts/list.js.php");
            request93.ThinkTime = 11;
            yield return request93;
            request93 = null;

            WebTestRequest request94 = new WebTestRequest("http://thuvien/admin/admincp_thuthu.php");
            request94.QueryStringParameters.Add("mod", "list_chitietphieumuon", false, false);
            request94.QueryStringParameters.Add("NxT_MaPhieuMuon", "3", false, false);
            request94.QueryStringParameters.Add("KT_back", "1", false, false);
            ExtractHiddenFields extractionRule14 = new ExtractHiddenFields();
            extractionRule14.Required = true;
            extractionRule14.HtmlDecode = true;
            extractionRule14.ContextParameterName = "1";
            request94.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule14.Extract);
            yield return request94;
            request94 = null;

            WebTestRequest request95 = new WebTestRequest("http://thuvien/includes/nxt/scripts/list.js.php");
            yield return request95;
            request95 = null;

            WebTestRequest request96 = new WebTestRequest("http://thuvien/includes/wdg/classes/MXWidgets.js.php");
            request96.ThinkTime = 9;
            yield return request96;
            request96 = null;

            WebTestRequest request97 = new WebTestRequest("http://thuvien/admin/admincp_form.php");
            request97.ExpectedResponseUrl = "http://thuvien/admin/admincp_form.php?NxT_MaPhieuMuon=3&mod=form_chitietphieumuon" +
                "&MaChiTietPhieuMuon=2";
            request97.QueryStringParameters.Add("NxT_MaPhieuMuon", "3", false, false);
            request97.QueryStringParameters.Add("mod", "form_chitietphieumuon", false, false);
            request97.QueryStringParameters.Add("MaChiTietPhieuMuon", this.Context["$HIDDEN1.MaChiTietPhieuMuon"].ToString(), false, false);
            request97.QueryStringParameters.Add("KT_back", "1", false, false);
            ExtractHiddenFields extractionRule15 = new ExtractHiddenFields();
            extractionRule15.Required = true;
            extractionRule15.HtmlDecode = true;
            extractionRule15.ContextParameterName = "1";
            request97.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule15.Extract);
            ExtractText extractionRule16 = new ExtractText();
            extractionRule16.StartsWith = "&MaChiTietPhieuMuon=";
            extractionRule16.EndsWith = "\"";
            extractionRule16.Index = 0;
            extractionRule16.IgnoreCase = false;
            extractionRule16.UseRegularExpression = false;
            extractionRule16.HtmlDecode = true;
            extractionRule16.Required = false;
            extractionRule16.ContextParameterName = "QueryStringParam44.MaChiTietPhieuMuon";
            request97.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule16.Extract);
            yield return request97;
            request97 = null;

            WebTestRequest request98 = new WebTestRequest("http://thuvien/includes/tng/scripts/FormValidation.js.php");
            yield return request98;
            request98 = null;

            WebTestRequest request99 = new WebTestRequest("http://thuvien/includes/wdg/classes/MXWidgets.js.php");
            request99.ThinkTime = 41;
            yield return request99;
            request99 = null;

            WebTestRequest request100 = new WebTestRequest("http://thuvien/admin/admincp_form.php");
            request100.Method = "POST";
            request100.ExpectedResponseUrl = "http://thuvien/admin/admincp_thuthu.php?mod=list_chitietphieumuon&NxT_MaPhieuMuon" +
                "=3&KT_back=1";
            request100.QueryStringParameters.Add("NxT_MaPhieuMuon", "3", false, false);
            request100.QueryStringParameters.Add("mod", "form_chitietphieumuon", false, false);
            request100.QueryStringParameters.Add("MaChiTietPhieuMuon", this.Context["QueryStringParam44.MaChiTietPhieuMuon"].ToString(), false, false);
            FormPostHttpBody request100Body = new FormPostHttpBody();
            request100Body.FormPostParameters.Add("MaLinhVuc_1", "11");
            request100Body.FormPostParameters.Add("MaNhom_1", "13");
            request100Body.FormPostParameters.Add("MaSach_1", "4");
            request100Body.FormPostParameters.Add("MaCuonSach_1", "8");
            request100Body.FormPostParameters.Add("NgayHetHan_1", "2010-10-23");
            request100Body.FormPostParameters.Add("NgayTra_1", "2010-12-17");
            request100Body.FormPostParameters.Add("TienPhat_1", "20 000");
            request100Body.FormPostParameters.Add("LyDoPhat_1", "- Tra wa han");
            request100Body.FormPostParameters.Add("TinhTrang_1", "1");
            request100Body.FormPostParameters.Add("kt_pk_chitietphieumuon_1", this.Context["$HIDDEN1.kt_pk_chitietphieumuon_1"].ToString());
            request100Body.FormPostParameters.Add("KT_Update1", "Cập nhật");
            request100Body.FormPostParameters.Add("KT_Update1", "Cập nhật");
            request100.Body = request100Body;
            yield return request100;
            request100 = null;

            WebTestRequest request101 = new WebTestRequest("http://thuvien/includes/nxt/scripts/list.js.php");
            yield return request101;
            request101 = null;

            WebTestRequest request102 = new WebTestRequest("http://thuvien/includes/wdg/classes/MXWidgets.js.php");
            request102.ThinkTime = 13;
            yield return request102;
            request102 = null;

            WebTestRequest request103 = new WebTestRequest("http://thuvien/includes/nxt/back.php");
            request103.ExpectedResponseUrl = "http://thuvien/admin/admincp_thuthu.php?mod=list_phieumuonthuthu";
            request103.QueryStringParameters.Add("KT_back", "-2", false, false);
            yield return request103;
            request103 = null;

            WebTestRequest request104 = new WebTestRequest("http://thuvien/includes/nxt/scripts/list.js.php");
            request104.ThinkTime = 13;
            yield return request104;
            request104 = null;

            WebTestRequest request105 = new WebTestRequest("http://thuvien/admin/admincp_thuthu.php");
            request105.QueryStringParameters.Add("mod", "list_chitietphieumuon", false, false);
            request105.QueryStringParameters.Add("NxT_MaPhieuMuon", "4", false, false);
            request105.QueryStringParameters.Add("KT_back", "1", false, false);
            ExtractHiddenFields extractionRule17 = new ExtractHiddenFields();
            extractionRule17.Required = true;
            extractionRule17.HtmlDecode = true;
            extractionRule17.ContextParameterName = "1";
            request105.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule17.Extract);
            yield return request105;
            request105 = null;

            WebTestRequest request106 = new WebTestRequest("http://thuvien/includes/nxt/scripts/list.js.php");
            yield return request106;
            request106 = null;

            WebTestRequest request107 = new WebTestRequest("http://thuvien/includes/wdg/classes/MXWidgets.js.php");
            request107.ThinkTime = 9;
            yield return request107;
            request107 = null;

            WebTestRequest request108 = new WebTestRequest("http://thuvien/admin/admincp_form.php");
            request108.ExpectedResponseUrl = "http://thuvien/admin/admincp_form.php?NxT_MaPhieuMuon=4&mod=form_chitietphieumuon" +
                "&MaChiTietPhieuMuon=5";
            request108.QueryStringParameters.Add("NxT_MaPhieuMuon", "4", false, false);
            request108.QueryStringParameters.Add("mod", "form_chitietphieumuon", false, false);
            request108.QueryStringParameters.Add("MaChiTietPhieuMuon", this.Context["$HIDDEN1.MaChiTietPhieuMuon"].ToString(), false, false);
            request108.QueryStringParameters.Add("KT_back", "1", false, false);
            ExtractHiddenFields extractionRule18 = new ExtractHiddenFields();
            extractionRule18.Required = true;
            extractionRule18.HtmlDecode = true;
            extractionRule18.ContextParameterName = "1";
            request108.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule18.Extract);
            yield return request108;
            request108 = null;

            WebTestRequest request109 = new WebTestRequest("http://thuvien/includes/tng/scripts/FormValidation.js.php");
            yield return request109;
            request109 = null;

            WebTestRequest request110 = new WebTestRequest("http://thuvien/includes/nxt/scripts/form.js.php");
            yield return request110;
            request110 = null;

            WebTestRequest request111 = new WebTestRequest("http://thuvien/includes/wdg/classes/MXWidgets.js.php");
            request111.ThinkTime = 71;
            yield return request111;
            request111 = null;

            WebTestRequest request112 = new WebTestRequest("http://thuvien/admin/admincp_form.php");
            request112.Method = "POST";
            request112.ExpectedResponseUrl = "http://thuvien/admin/admincp_thuthu.php?mod=list_chitietphieumuon&NxT_MaPhieuMuon" +
                "=4&KT_back=1";
            request112.QueryStringParameters.Add("NxT_MaPhieuMuon", "4", false, false);
            request112.QueryStringParameters.Add("mod", "form_chitietphieumuon", false, false);
            request112.QueryStringParameters.Add("MaChiTietPhieuMuon", "5", false, false);
            FormPostHttpBody request112Body = new FormPostHttpBody();
            request112Body.FormPostParameters.Add("MaLinhVuc_1", "11");
            request112Body.FormPostParameters.Add("MaNhom_1", "14");
            request112Body.FormPostParameters.Add("MaSach_1", "8");
            request112Body.FormPostParameters.Add("MaCuonSach_1", "14");
            request112Body.FormPostParameters.Add("NgayHetHan_1", "2010-10-24");
            request112Body.FormPostParameters.Add("NgayTra_1", "2010-12-17");
            request112Body.FormPostParameters.Add("TienPhat_1", "30 000");
            request112Body.FormPostParameters.Add("LyDoPhat_1", "- Sach hu \r\n- Tra qua han");
            request112Body.FormPostParameters.Add("TinhTrang_1", "1");
            request112Body.FormPostParameters.Add("kt_pk_chitietphieumuon_1", this.Context["$HIDDEN1.kt_pk_chitietphieumuon_1"].ToString());
            request112Body.FormPostParameters.Add("KT_Update1", "Cập nhật");
            request112Body.FormPostParameters.Add("KT_Update1", "Cập nhật");
            request112.Body = request112Body;
            yield return request112;
            request112 = null;

            WebTestRequest request113 = new WebTestRequest("http://thuvien/includes/nxt/scripts/list.js.php");
            yield return request113;
            request113 = null;

            WebTestRequest request114 = new WebTestRequest("http://thuvien/includes/wdg/classes/MXWidgets.js.php");
            request114.ThinkTime = 63;
            yield return request114;
            request114 = null;

            WebTestRequest request115 = new WebTestRequest("http://thuvien/includes/nxt/back.php");
            request115.ExpectedResponseUrl = "http://thuvien/admin/admincp_thuthu.php?mod=list_phieumuonthuthu";
            request115.QueryStringParameters.Add("KT_back", "-2", false, false);
            yield return request115;
            request115 = null;

            WebTestRequest request116 = new WebTestRequest("http://thuvien/includes/nxt/scripts/list.js.php");
            request116.ThinkTime = 4;
            yield return request116;
            request116 = null;

            WebTestRequest request117 = new WebTestRequest("http://thuvien/admin/admincp_thuthu.php");
            request117.QueryStringParameters.Add("mod", "form_thongke", false, false);
            ExtractHiddenFields extractionRule19 = new ExtractHiddenFields();
            extractionRule19.Required = true;
            extractionRule19.HtmlDecode = true;
            extractionRule19.ContextParameterName = "1";
            request117.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule19.Extract);
            yield return request117;
            request117 = null;

            WebTestRequest request118 = new WebTestRequest("http://thuvien/includes/wdg/classes/MXWidgets.js.php");
            request118.ThinkTime = 2;
            yield return request118;
            request118 = null;

            WebTestRequest request119 = new WebTestRequest("http://thuvien/admin/admincp_thuthu.php");
            request119.ThinkTime = 5;
            request119.QueryStringParameters.Add("mod", this.Context["$HIDDEN1.mod"].ToString(), false, false);
            request119.QueryStringParameters.Add("key2", "4", false, false);
            request119.QueryStringParameters.Add("key3", "All", false, false);
            request119.QueryStringParameters.Add("key4", "", false, false);
            request119.QueryStringParameters.Add("key5", "", false, false);
            yield return request119;
            request119 = null;

            WebTestRequest request120 = new WebTestRequest("http://thuvien/admin/admincp_thuthu.php");
            request120.QueryStringParameters.Add("mod", "form_thongke", false, false);
            ExtractHiddenFields extractionRule20 = new ExtractHiddenFields();
            extractionRule20.Required = true;
            extractionRule20.HtmlDecode = true;
            extractionRule20.ContextParameterName = "1";
            request120.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule20.Extract);
            yield return request120;
            request120 = null;

            WebTestRequest request121 = new WebTestRequest("http://thuvien/includes/wdg/classes/MXWidgets.js.php");
            request121.ThinkTime = 3;
            yield return request121;
            request121 = null;

            WebTestRequest request122 = new WebTestRequest("http://thuvien/admin/admincp_thuthu.php");
            request122.ThinkTime = 4;
            request122.QueryStringParameters.Add("mod", this.Context["$HIDDEN1.mod"].ToString(), false, false);
            request122.QueryStringParameters.Add("key2", "11", false, false);
            request122.QueryStringParameters.Add("key3", "All", false, false);
            request122.QueryStringParameters.Add("key4", "", false, false);
            request122.QueryStringParameters.Add("key5", "", false, false);
            yield return request122;
            request122 = null;

            WebTestRequest request123 = new WebTestRequest("http://thuvien/admin/admincp_thuthu.php");
            request123.QueryStringParameters.Add("mod", "form_thongkedocgia", false, false);
            ExtractHiddenFields extractionRule21 = new ExtractHiddenFields();
            extractionRule21.Required = true;
            extractionRule21.HtmlDecode = true;
            extractionRule21.ContextParameterName = "1";
            request123.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule21.Extract);
            yield return request123;
            request123 = null;

            WebTestRequest request124 = new WebTestRequest("http://thuvien/includes/wdg/classes/MXWidgets.js.php");
            request124.ThinkTime = 1;
            yield return request124;
            request124 = null;

            WebTestRequest request125 = new WebTestRequest("http://thuvien/admin/admincp_thuthu.php");
            request125.ThinkTime = 4;
            request125.QueryStringParameters.Add("mod", this.Context["$HIDDEN1.mod"].ToString(), false, false);
            request125.QueryStringParameters.Add("key4", "", false, false);
            request125.QueryStringParameters.Add("key5", "", false, false);
            yield return request125;
            request125 = null;

            WebTestRequest request126 = new WebTestRequest("http://thuvien/index.php");
            yield return request126;
            request126 = null;

            WebTestRequest request127 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            yield return request127;
            request127 = null;

            WebTestRequest request128 = new WebTestRequest("http://thuvien/images/clip2.swf");
            request128.ThinkTime = 5;
            yield return request128;
            request128 = null;

            WebTestRequest request129 = new WebTestRequest("http://thuvien/index.php");
            request129.ExpectedResponseUrl = "http://thuvien/index.php";
            request129.QueryStringParameters.Add("KT_logout_now", "1", false, false);
            yield return request129;
            request129 = null;

            WebTestRequest request130 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            yield return request130;
            request130 = null;

            WebTestRequest request131 = new WebTestRequest("http://thuvien/includes/wdg/classes/MXWidgets.js.php");
            yield return request131;
            request131 = null;

            WebTestRequest request132 = new WebTestRequest("http://thuvien/images/clip2.swf");
            request132.ThinkTime = 9;
            yield return request132;
            request132 = null;

            WebTestRequest request133 = new WebTestRequest("http://thuvien/index.php");
            ExtractText extractionRule22 = new ExtractText();
            extractionRule22.StartsWith = "?mod=";
            extractionRule22.EndsWith = "\"";
            extractionRule22.Index = 6;
            extractionRule22.IgnoreCase = false;
            extractionRule22.UseRegularExpression = false;
            extractionRule22.HtmlDecode = true;
            extractionRule22.Required = false;
            extractionRule22.ContextParameterName = "QueryStringParam250.mod";
            request133.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule22.Extract);
            yield return request133;
            request133 = null;

            WebTestRequest request134 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            yield return request134;
            request134 = null;

            WebTestRequest request135 = new WebTestRequest("http://thuvien/images/clip2.swf");
            request135.ThinkTime = 641;
            yield return request135;
            request135 = null;

            WebTestRequest request136 = new WebTestRequest("http://thuvien/index.php");
            request136.QueryStringParameters.Add("mod", this.Context["QueryStringParam250.mod"].ToString(), false, false);
            ExtractText extractionRule23 = new ExtractText();
            extractionRule23.StartsWith = "?mod=";
            extractionRule23.EndsWith = "&";
            extractionRule23.Index = 8;
            extractionRule23.IgnoreCase = false;
            extractionRule23.UseRegularExpression = false;
            extractionRule23.HtmlDecode = true;
            extractionRule23.Required = false;
            extractionRule23.ContextParameterName = "QueryStringParam15.mod";
            request136.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule23.Extract);
            yield return request136;
            request136 = null;

            WebTestRequest request137 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request137.ThinkTime = 17;
            yield return request137;
            request137 = null;

            WebTestRequest request138 = new WebTestRequest("http://thuvien/index.php");
            request138.ExpectedResponseUrl = "http://thuvien/index.php";
            request138.QueryStringParameters.Add("mod", this.Context["QueryStringParam15.mod"].ToString(), false, false);
            request138.QueryStringParameters.Add("KT_logout_now", "1", false, false);
            yield return request138;
            request138 = null;

            WebTestRequest request139 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            yield return request139;
            request139 = null;

            WebTestRequest request140 = new WebTestRequest("http://thuvien/images/clip2.swf");
            request140.ThinkTime = 12;
            yield return request140;
            request140 = null;

            WebTestRequest request141 = new WebTestRequest("http://thuvien/index.php");
            ExtractText extractionRule24 = new ExtractText();
            extractionRule24.StartsWith = "?mod=";
            extractionRule24.EndsWith = "\"";
            extractionRule24.Index = 6;
            extractionRule24.IgnoreCase = false;
            extractionRule24.UseRegularExpression = false;
            extractionRule24.HtmlDecode = true;
            extractionRule24.Required = false;
            extractionRule24.ContextParameterName = "QueryStringParam251.mod";
            request141.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule24.Extract);
            yield return request141;
            request141 = null;

            WebTestRequest request142 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            yield return request142;
            request142 = null;

            WebTestRequest request143 = new WebTestRequest("http://thuvien/images/clip2.swf");
            request143.ThinkTime = 7;
            yield return request143;
            request143 = null;

            WebTestRequest request144 = new WebTestRequest("http://thuvien/index.php");
            request144.QueryStringParameters.Add("mod", this.Context["QueryStringParam251.mod"].ToString(), false, false);
            ExtractText extractionRule25 = new ExtractText();
            extractionRule25.StartsWith = "?mod=";
            extractionRule25.EndsWith = "\"";
            extractionRule25.Index = 6;
            extractionRule25.IgnoreCase = false;
            extractionRule25.UseRegularExpression = false;
            extractionRule25.HtmlDecode = true;
            extractionRule25.Required = false;
            extractionRule25.ContextParameterName = "QueryStringParam12.mod";
            request144.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule25.Extract);
            yield return request144;
            request144 = null;

            WebTestRequest request145 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request145.ThinkTime = 10;
            yield return request145;
            request145 = null;

            WebTestRequest request146 = new WebTestRequest("http://thuvien/index.php");
            request146.QueryStringParameters.Add("mod", this.Context["QueryStringParam12.mod"].ToString(), false, false);
            ExtractText extractionRule26 = new ExtractText();
            extractionRule26.StartsWith = "?mod=";
            extractionRule26.EndsWith = "\"";
            extractionRule26.Index = 5;
            extractionRule26.IgnoreCase = false;
            extractionRule26.UseRegularExpression = false;
            extractionRule26.HtmlDecode = true;
            extractionRule26.Required = false;
            extractionRule26.ContextParameterName = "QueryStringParam11.mod";
            request146.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule26.Extract);
            ExtractFormField extractionRule27 = new ExtractFormField();
            extractionRule27.Name = "Email";
            extractionRule27.HtmlDecode = true;
            extractionRule27.Required = false;
            extractionRule27.ContextParameterName = "FormPostParam1.Email";
            request146.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule27.Extract);
            ExtractFormField extractionRule28 = new ExtractFormField();
            extractionRule28.Name = "KT_Update1";
            extractionRule28.HtmlDecode = true;
            extractionRule28.Required = false;
            extractionRule28.ContextParameterName = "FormPostParam3.KT_Update1";
            request146.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule28.Extract);
            yield return request146;
            request146 = null;

            WebTestRequest request147 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            yield return request147;
            request147 = null;

            WebTestRequest request148 = new WebTestRequest("http://thuvien/includes/wdg/classes/MXWidgets.js.php");
            yield return request148;
            request148 = null;

            WebTestRequest request149 = new WebTestRequest("http://thuvien/includes/tng/scripts/FormValidation.js.php");
            request149.ThinkTime = 20;
            yield return request149;
            request149 = null;

            WebTestRequest request150 = new WebTestRequest("http://thuvien/index.php");
            request150.Method = "POST";
            request150.QueryStringParameters.Add("mod", this.Context["QueryStringParam11.mod"].ToString(), false, false);
            FormPostHttpBody request150Body = new FormPostHttpBody();
            request150Body.FormPostParameters.Add("old_Pass", "123456789");
            request150Body.FormPostParameters.Add("Pass", "123456");
            request150Body.FormPostParameters.Add("re_Pass", "123456");
            request150Body.FormPostParameters.Add("Email", this.Context["FormPostParam1.Email"].ToString());
            request150Body.FormPostParameters.Add("SoDienThoai", "01682016073");
            request150Body.FormPostParameters.Add("KT_Update1", this.Context["FormPostParam3.KT_Update1"].ToString());
            request150.Body = request150Body;
            yield return request150;
            request150 = null;

            WebTestRequest request151 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            request151.ThinkTime = 2;
            yield return request151;
            request151 = null;

            WebTestRequest request152 = new WebTestRequest("http://thuvien/index.php");
            yield return request152;
            request152 = null;

            WebTestRequest request153 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            yield return request153;
            request153 = null;

            WebTestRequest request154 = new WebTestRequest("http://thuvien/images/clip2.swf");
            request154.ThinkTime = 5;
            yield return request154;
            request154 = null;

            WebTestRequest request155 = new WebTestRequest("http://thuvien/admin/admincp1.php");
            request155.ThinkTime = 9;
            yield return request155;
            request155 = null;

            WebTestRequest request156 = new WebTestRequest("http://thuvien/admin/admincp1.php");
            request156.QueryStringParameters.Add("mod", "list_lienhewebsite", false, false);
            yield return request156;
            request156 = null;

            WebTestRequest request157 = new WebTestRequest("http://thuvien/includes/nxt/scripts/list.js.php");
            request157.ThinkTime = 13;
            yield return request157;
            request157 = null;

            WebTestRequest request158 = new WebTestRequest("http://thuvien/admin/admincp1.php");
            request158.QueryStringParameters.Add("mod", "list_thanhvien", false, false);
            yield return request158;
            request158 = null;

            WebTestRequest request159 = new WebTestRequest("http://thuvien/includes/nxt/scripts/list.js.php");
            request159.ThinkTime = 7;
            yield return request159;
            request159 = null;

            WebTestRequest request160 = new WebTestRequest("http://thuvien/admin/admincp1.php");
            request160.QueryStringParameters.Add("mod", "list_khoa", false, false);
            yield return request160;
            request160 = null;

            WebTestRequest request161 = new WebTestRequest("http://thuvien/includes/nxt/scripts/list.js.php");
            request161.ThinkTime = 12;
            yield return request161;
            request161 = null;

            WebTestRequest request162 = new WebTestRequest("http://thuvien/index.php");
            yield return request162;
            request162 = null;

            WebTestRequest request163 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            yield return request163;
            request163 = null;

            WebTestRequest request164 = new WebTestRequest("http://thuvien/images/clip2.swf");
            request164.ThinkTime = 16;
            yield return request164;
            request164 = null;

            WebTestRequest request165 = new WebTestRequest("http://thuvien/index.php");
            request165.ExpectedResponseUrl = "http://thuvien/index.php";
            request165.QueryStringParameters.Add("KT_logout_now", "1", false, false);
            yield return request165;
            request165 = null;

            WebTestRequest request166 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            yield return request166;
            request166 = null;

            WebTestRequest request167 = new WebTestRequest("http://thuvien/includes/wdg/classes/MXWidgets.js.php");
            yield return request167;
            request167 = null;

            WebTestRequest request168 = new WebTestRequest("http://thuvien/images/clip2.swf");
            yield return request168;
            request168 = null;

            WebTestRequest request169 = new WebTestRequest("http://thuvien/includes/tng/scripts/FormValidation.js.php");
            request169.ThinkTime = 18;
            yield return request169;
            request169 = null;

            WebTestRequest request170 = new WebTestRequest("http://thuvien/index.php");
            yield return request170;
            request170 = null;

            WebTestRequest request171 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            yield return request171;
            request171 = null;

            WebTestRequest request172 = new WebTestRequest("http://thuvien/includes/wdg/classes/MXWidgets.js.php");
            yield return request172;
            request172 = null;

            WebTestRequest request173 = new WebTestRequest("http://thuvien/images/clip2.swf");
            yield return request173;
            request173 = null;

            WebTestRequest request174 = new WebTestRequest("http://thuvien/includes/tng/scripts/FormValidation.js.php");
            request174.ThinkTime = 11;
            yield return request174;
            request174 = null;

            WebTestRequest request175 = new WebTestRequest("http://thuvien/admin/admincp_bpnhapsach.php");
            request175.ThinkTime = 8;
            yield return request175;
            request175 = null;

            WebTestRequest request176 = new WebTestRequest("http://thuvien/admin/admincp_bpnhapsach.php");
            request176.QueryStringParameters.Add("mod", "list_linhvuc", false, false);
            yield return request176;
            request176 = null;

            WebTestRequest request177 = new WebTestRequest("http://thuvien/includes/nxt/scripts/list.js.php");
            request177.ThinkTime = 7;
            yield return request177;
            request177 = null;

            WebTestRequest request178 = new WebTestRequest("http://thuvien/admin/admincp_bpnhapsach.php");
            request178.QueryStringParameters.Add("mod", "list_nhomsach", false, false);
            yield return request178;
            request178 = null;

            WebTestRequest request179 = new WebTestRequest("http://thuvien/includes/nxt/scripts/list.js.php");
            request179.ThinkTime = 5;
            yield return request179;
            request179 = null;

            WebTestRequest request180 = new WebTestRequest("http://thuvien/admin/admincp_bpnhapsach.php");
            request180.QueryStringParameters.Add("mod", "list_sach", false, false);
            yield return request180;
            request180 = null;

            WebTestRequest request181 = new WebTestRequest("http://thuvien/includes/nxt/scripts/list.js.php");
            request181.ThinkTime = 5;
            yield return request181;
            request181 = null;

            WebTestRequest request182 = new WebTestRequest("http://thuvien/index.php");
            yield return request182;
            request182 = null;

            WebTestRequest request183 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            yield return request183;
            request183 = null;

            WebTestRequest request184 = new WebTestRequest("http://thuvien/includes/wdg/classes/MXWidgets.js.php");
            yield return request184;
            request184 = null;

            WebTestRequest request185 = new WebTestRequest("http://thuvien/images/clip2.swf");
            request185.ThinkTime = 5;
            yield return request185;
            request185 = null;

            WebTestRequest request186 = new WebTestRequest("http://thuvien/index.php");
            request186.ExpectedResponseUrl = "http://thuvien/index.php";
            request186.QueryStringParameters.Add("KT_logout_now", "1", false, false);
            yield return request186;
            request186 = null;

            WebTestRequest request187 = new WebTestRequest("http://thuvien/images/flashbanner.swf");
            yield return request187;
            request187 = null;

            WebTestRequest request188 = new WebTestRequest("http://thuvien/images/clip2.swf");
            yield return request188;
            request188 = null;
        }
    }
}
